export const Users = [
  {
    id: 1,
    profilePicture: "assets/Post/abiy.jpg",
    username: "Abiy Menberu",
  },
  {
    id: 2,
    profilePicture: "assets/Person/dan.jpg",
    username: "Dan Mekonnen",
  },
  {
    id: 3,
    profilePicture: "assets/Person/ermias.jpg",
    username: "Ermias Asmare",
  },
  {
    id: 4,
    profilePicture: "assets/Person/maruf.jpg",
    username: "Maruf Sherifa",
  },
  {
    id: 5,
    profilePicture: "assets/Person/redi_post2.jpg",
    username: "Rediate Befekadu",
  },
  {
    id: 6,
    profilePicture: "assets/Person/sintayehu.jpg",
    username: "Sintayehu Sermessa",
  },
  {
    id: 7,
    profilePicture: "assets/Person/abiy.jpg",
    username: "Abiy Alemayew",
  },
  {
    id: 8,
    profilePicture: "assets/Person/maruf.jpg",
    username: "Maruf Markose",
  },
  {
    id: 9,
    profilePicture: "assets/Person/sintayehu.jpg",
    username: "Sintayehu Bokiso",
  },
  {
    id: 10,
    profilePicture: "assets/Person/redi_post2.jpg",
    username: "Rediate Techala",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Love For All, Hatred For None.",
    photo: "assets/Post/abiy.jpg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    desc: "Chela kids book",
    photo: "assets/Post/chala.jpg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo: "assets/Post/ermias.jpg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    desc: "Every moment is a fresh beginning.",
    photo: "assets/Post/maruf-post.jpg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "assets/Post/redi_post.jpg",
    desc: "Every moment is a fresh beginning.",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "assets/Post/blockchain.png",
    date: "1 day ago",
    userId: 6,
    desc: "Every moment is a fresh beginning.",
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: "assets/Post/dan_post.jpg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "assets/Post/maruf-post.jpg",
    date: "3 days ago",
    desc: "Every moment is a fresh beginning.",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Change the world by being yourself.",
    photo: "assets/Post/sintayehu.jpg",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    desc: "Every moment is a fresh beginning.",
    photo: "assets/Person/redi_post2.jpg",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];
